enum ConfigKey {
    PORT = 'PORT',
    BASE_PATH = 'BASE_PATH',
    JWT_ACCESS_TOKEN_SECRET_KEY = 'JWT_ACCESS_TOKEN_SECRET_KEY',
    JWT_REFRESH_TOKEN_SECRET_KEY = 'JWT_REFRESH_TOKEN_SECRET_KEY',
    JWT_ACCESS_TOKEN_EXPIRED_IN = 'JWT_ACCESS_TOKEN_EXPIRED_IN',
    JWT_REFRESH_TOKEN_EXPIRED_IN = 'JWT_REFRESH_TOKEN_EXPIRED_IN',
    MONGODB_CONNECTION_STRING = 'MONGODB_CONNECTION_STRING',
    DB_DEBUG = 'DB_DEBUG',
    CORS_WHITELIST = 'CORS_WHITELIST',
    WEB_APP_BASE_URL = 'WEB_APP_BASE_URL',
}
export default ConfigKey;
