enum ConfigKey {
    PORT = 'PORT',
    BASE_PATH = 'BASE_PATH',
    VERSION = 'VERSION',
    MONGODB_CONNECTION_STRING = 'MONGODB_CONNECTION_STRING',
    MONGO_DEBUG = 'MONGO_DEBUG',
    CORS_WHITELIST = 'CORS_WHITELIST',
    WEB_APP_BASE_URL = 'WEB_APP_BASE_URL',
    JWT_ACCESS_TOKEN_SECRET_KEY = 'JWT_ACCESS_TOKEN_SECRET_KEY',
    JWT_REFRESH_TOKEN_SECRET_KEY = 'JWT_REFRESH_TOKEN_SECRET_KEY',
    JWT_ACCESS_TOKEN_EXPIRED_IN = 'JWT_ACCESS_TOKEN_EXPIRED_IN',
    JWT_REFRESH_TOKEN_EXPIRED_IN = 'JWT_REFRESH_TOKEN_EXPIRED_IN',
    PRODUCT_WARRANTY_TIME_IN_YEAR = 'PRODUCT_WARRANTY_TIME_IN_YEAR',
    TIMEZONE_DEFAULT = 'TIMEZONE_DEFAULT',
    TIMEZONE_DEFAULT_NAME = 'TIMEZONE_DEFAULT_NAME',
}
export default ConfigKey;
